name: Repository Dispatch
on:
  repository_dispatch:
    types: [trigger-example-project]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.event.client_payload.sha }}